language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - unset PERL_CPANM_OPT
    - "echo 'user CHIM' > ~/.pause"
    - "git config user.email 'chim@cpan.org'"
    - "git config user.name 'Anton Gerasimov'"
    - "perlbrew --force install-cpanm"
    - "cpanm --version"
    - "cpanm -q -n version"
    - "cpanm -q -n Pod::Readme"
    - "cpanm -q -n Test::CPAN::Meta"
    - "cpanm -q -n Test::Kwalitee"
    - "cpanm -q -n Test::Pod::Coverage"
    - "cpanm -q -n Test::Pod"
    - "cpanm -q -n Test::EOL"
    - "cpanm -q -n Test::NoTabs"
    - "cpanm -q -n Pod::Coverage::TrustPod"
    - "cpanm -q -n Dist::Zilla::PluginBundle::Author::CHIM"
    - "cpanm -q -n Test::Pod::Coverage"

install:
    - "dzil authordeps --missing | xargs cpanm -q -n"
    - "dzil listdeps | xargs cpanm -q -n"

script:
    - "dzil test --release"

after_success:
    - "cpanm -q -n Dist::Zilla::App::Command::cover Devel::Cover::Report::Coveralls"
    - "dzil cover -report coveralls"
