language: perl

perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - unset PERL_CPANM_OPT
    - "cpanm --mirror http://cpan.stratopan.com -q -n Dist::Zilla::PluginBundle::Author::CHIM"
    - "cpanm --mirror http://cpan.stratopan.com -q -n Test::Pod::Coverage"

install:
    - "dzil authordeps --missing | xargs cpanm --mirror http://cpan.stratopan.com -q -n && dzil listdeps | xargs cpanm --mirror http://cpan.stratopan.com -q -n"

script:
    - "dzil smoke --release --author"

after_success:
    - "cpanm --mirror http://cpan.stratopan.com -q -n Dist::Zilla::App::Command::cover Devel::Cover::Report::Coveralls"
    - "dzil cover -report coveralls"
